services:
  postgres-customer:
    container_name: postgres-graph
    image: postgres
    environment:
      POSTGRES_USER: graphql
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-graph:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres-graph:
